name: Pull Secrets
on: 
  [push]
jobs:
  Pull-Secrets:
    runs-on: ubuntu-latest
    steps:
      # List out repository details
      - name: Step 1 - Echo out a GitHub Actions Secret to the logs
        run: |
          echo "The job was automatically triggered by a ${{ github.event_name }} event."
          echo "This job is now running on a ${{ runner.os }} server hosted by GitHub!"
          echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
          
      # Check out repository code
      - name: Step 2 - Check out repository code
        id: pull_secrets
        uses: actions/checkout@v2
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          repository: 'jvsrikanth11/scrs-configurer'
          ref: main
          token: ${{ secrets.ACCESS_TOKEN }}
          
      - name: view the secrets context
        run: echo "$SECRETS_CONTEXT"
        env:
          SECRETS_CONTEXT: ${{ toJson(secrets) }}
